applicationSh:
  service:
    catalogue:
      uri: http://localhost:8081
      username: user
      password: ppar
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/manager
    username: manager
    password: manager
